### ISSUE TITLE
能否增加“批量消除声音”的选项？

### ISSUE THREAD

**Issue by joomlagate** [zymill/ffmpeg_hys#1]
有时候需要对多个视频文件进行“批量消声”（删除音频仅保留无声画面）的操作。能否在这个批处理文件中增加这个选项？

消声处理后将输出文件保存在原始文件同名文件夹，或者该文件夹的子文件夹里面，文件名可以增加 -mute 后缀以便区分。

谢谢！

**Comment by zymill** [comment]
当然可以的。可以参考现在的文本，修改为去掉音频，存储到指定路径。
